# This is a basic workflow to help you get started with Actions

name: Compile to PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths: '**.tex'
  pull_request:
    branches: [ "master" ]
    paths: '**.tex'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        id: compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Shchepetnov_CV.tex
          
      - name: Commit and Push Changes
        if: steps.compile.outcome == 'success'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          timestamp=$(date +'%Y%m%d%H%M%S')
          branch_name="update-pdf-$timestamp"
      
          git checkout -b "$branch_name"
      
          git add Shchepetnov_CV.pdf
      
          git commit -m "Update PDF"
      
          git push origin "$branch_name"
      
          git checkout main
          git merge --no-ff "$branch_name"
          git push origin main
      
          # delete the temporary branch
          git branch -d "$branch_name"
          git push origin --delete "$branch_name"
